import { ShahrazadPlaymatId } from './playmat';
import { ShahrazadZoneId } from './zone';
export type ShahrazadCard = { state: ShahrazadCardOptions;
    card_name: ShahrazadCardName; location: ShahrazadZoneId;
    owner: ShahrazadPlaymatId };
export type ShahrazadCardId = string;
export type ShahrazadCardName = string;
export type ShahrazadCardOptions = { inverted?: boolean; flipped?: boolean;
    tapped?: boolean; face_down?: boolean; x?: number; y?: number;
    counters?: Array<ShahrazadCounter> };
export type ShahrazadCounter = { amount: number };
