import { ShahrazadCard } from './card';
import { ShahrazadPlaymat, ShahrazadPlaymatId } from './playmat';
import { ShahrazadZone, ShahrazadZoneId } from './zone';
type usize = number;
export type ShahrazadGame = { zone_count: usize; card_count: usize;
    cards: Array<ShahrazadCard>; zones: Array<ShahrazadZone>;
    playmats: Array<ShahrazadPlaymat>; players: Array<ShahrazadPlaymatId>;
    settings: ShahrazadGameSettings; created_at: number;
    stack: ShahrazadZoneId };
export type ShahrazadGameSettings = { starting_life: number;
    free_mulligans: number; commander: boolean; scry_rule: boolean };
