// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShahrazadZoneId } from "./ShahrazadZoneId";

export type ShahrazadPlaymat = { library: ShahrazadZoneId, hand: ShahrazadZoneId, graveyard: ShahrazadZoneId, battlefield: ShahrazadZoneId, exile: ShahrazadZoneId, command: ShahrazadZoneId, };
