// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShahrazadCardId } from "./ShahrazadCardId";

export type ShahrazadZone = { cards: Array<ShahrazadCardId>, };
