// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ShahrazadCardOptions = { inverted: boolean | null, flipped: boolean | null, tapped: boolean | null, face_down: boolean | null, x: number | null, y: number | null, };
