// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CardName } from "./CardName";
import type { ShahrazadZoneId } from "./ShahrazadZoneId";

export type ShahrazadCard = { card_name: CardName, location: ShahrazadZoneId, inverted: boolean | null, flipped: boolean | null, tapped: boolean | null, face_down: boolean | null, x: number | null, y: number | null, };
