// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShahrazadCardId } from "./ShahrazadCardId";
import type { ShahrazadCardOptions } from "./ShahrazadCardOptions";
import type { ShahrazadZoneId } from "./ShahrazadZoneId";

export type ShahrazadAction =
    | {
          DrawBottom: {
              amount: number;
              source: ShahrazadZoneId;
              destination: ShahrazadZoneId;
          };
      }
    | {
          DrawTop: {
              amount: number;
              source: ShahrazadZoneId;
              destination: ShahrazadZoneId;
          };
      }
    | {
          CardState: {
              cards: Array<ShahrazadCardId>;
              state: ShahrazadCardOptions;
          };
      }
    | {
          CardZone: {
              cards: Array<ShahrazadCardId>;
              state: ShahrazadCardOptions;
              source: ShahrazadZoneId;
              destination: ShahrazadZoneId;
              index: number;
          };
      }
    | { Shuffle: { zone: ShahrazadZoneId; seed: number } }
    | { ZoneImport: { zone: ShahrazadZoneId; cards: Array<string> } }
    | { DeckImport: { deck_uri: string; player_idx: number } }
    | "AddPlayer";
