syntax = "proto3";
package game;

import "src/proto/card.proto";
import "src/proto/playmat.proto";
import "src/proto/zone.proto";

message ShahrazadGameSettings {
    int32 starting_life = 1;
    int32 free_mulligans = 2;
    bool commander = 3;
    bool scry_rule = 4;
}

message ShahrazadGame {
    uint32 zone_count = 1;
    uint32 card_count = 2;
    repeated card.ShahrazadCard cards = 3;
    repeated zone.ShahrazadZone zones = 4;
    repeated playmat.ShahrazadPlaymat playmats = 5;
    repeated uint32 players = 6;
    ShahrazadGameSettings settings = 7;
    uint64 created_at = 8;
    uint32 stack = 9;
}