[package]
name = "shared"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1.0", features = ["derive"]}
type_reflect = "0.3.0"

[dev-dependencies]
pretty_assertions = "1"