[package]
name = "shared"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1.0", features = ["derive"]}
type_reflect = "0.3.0"
uuid = { version = "1.6", features = ["v4", "serde"] }
rand = "0.8"
rand_chacha = "0.3"


[dev-dependencies]
pretty_assertions = "1"